### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jlew715/helper_methods#1]
I'm seeing a lot of specification failures locally. Did you read [the _How to work on this_ section of the README](https://github.com/chrisvfritz/tc359_helper_methods#how-to-work-on-this)? By following those instructions, you should be able to guarantee that everything is working as it should.

Let me know if you encounter any problems or get stuck and I'll be happy to point you in the right direction.

**Comment by jlew715** [comment]
Should be all good now - no errors in the console (heroku or locally), web inspector (heroku or locally), or the heroku logs.

For what it’s worth, the only error I could see in any of those locations before was some CSS token errors. Where were you seeing the specification failures?

Jerold

**Comment by chrisvfritz** [comment]
The specs are _almost_ fixed. You need to remove not only `:pending`, but also the comma before `:pending` in each spec file. If you do that and then run `bundle exec rspec` from the project folder, you should see all of the areas where a method isn't quite doing what it's meant to.

**Comment by jlew715** [comment]
I got the bootstrap alert method to pass validation, but I don’t know for the current_date_and_time one how to format it the way the validator wants, i.e. inserting the “at”, etc. image_tag method passes none of the validations, and just gives me a "undefined method `url' for nil:NilClass” for each test. I’m not quite sure how to proceed.

If you have any pointers, I’d be happy to take a crack at it tomorrow or if you’d rather just meet later this week, that would be fine too.

**Comment by chrisvfritz** [comment]
The `image_tag` method is _really_ close. My tip for that one is to remember that in the future, we might want to be able to use this helper for a non-cat image as well. In those cases, we won't want to use the `url` from a `@cat_image` instance variable, since it won't always exist. Instead, we might want to pass in  a different source like this:

``` erb
<%= image_tag 'http://example.com/image.jpg', 'Example image' %>
```

Can you think of a way to modify the method to make that possible? Make sure to bring your kitten over before testing this one again. :smile: 

I have a few tips for the `current_date_and_time` method. The first is to try using `Time.now` instead of `Time.new`. They'll do the same thing when passed now arguments, but it's convention to use the former when you just want the current time and the specs also assume that's what you're using.

The second tip is that you can actually type in type letters, spaces, and special characters into what you pass to `strftime`, like so:

``` ruby
Time.now.strftime('Printed on %m/%d/%Y')
# => "Printed on 11/19/2007"
```

This way, you don't have to concatenate the results of a bunch of calls to `strftime`.

Finally, my last tip is that the `-` flag may be useful to you here. It removes any unwanted padding (like 0 padding or space padding) for output that could contain either 1 or 2 digits. For example, if I wanted to grab the month as a number, I could do so with:

``` ruby
Time.now.strftime('%m')
# => "03"
```

It gives me 3 with a zero padding. If I want to get rid of it, I can add that hyphen between the `%` and the `m`, like so:

``` ruby
Time.now.strftime('%-m')
# => "3"
```

Let me know if that helps!

**Comment by jlew715** [comment]
Extremely helpful, thanks! All the methods pass validation now, so I should be good for that assignment. I’ll take a crack at the Rails one today or tomorrow and let you know if I get absolutely stuck. 

Thanks!
Jerold

**Comment by chrisvfritz** [comment]
:+1: Looks great!
